### ISSUE TITLE
关于抽离出请求层的问题？

### ISSUE THREAD

**Issue by fengmumu1** [Vincedream/ddd-fe-demo#5]
每个页面都有接口按照领域去划分是可以划分的，但是接口还是独立的，也就是说，都是用户信息，每个页面需求的信息仍然不尽相同，所以各自有各自的接口是合理且高效的，那么此时的数据已经和页面有绑定关系了，如果再抽离一个数据处理层，那么为了使这个处理函数可以多处复用，势必要多处判断，时时修改（需求不会一成不变），然后这个数据清洗函数其实也是和页面相互绑定的（清理好后的数据应该直接被渲染【根据文章所描述】）
综上：一个和页面有关的请求，和一个和请求结果以及页面相关的数据清理函数，以及最后要用的页面，为什么要分开三处写？

**Comment by betgar** [comment]
你的这个问题很好回答，其实只需要转变一下思路即可。按照模块化的思想，把这个分层移转换为如下结构，我自己分的。
```
fe-domain
└── src
    ├── api  # 全局api，可以隔离模块内部api和外部api
    │   ├── api.js   
    │   └── modules
    │       └── UserPublicApi.js
    ├── App.vue
    ├── common   # 公共模块
    │   └── http.js
    ├── components  # 组件
    │   ├── Nav.vue
    │   └── Table.vue
    ├── main.js
    ├── modules  # 模块
    │   └── user   
    │       ├── api  # user 模块api层，public + private api都在这里集中
    │       │   └── UserApi.js
    │       ├── common
    │       │   └── utils.js
    │       ├── components
    │       │   ├── Avatar.vue
    │       │   └── List.vue
    │       ├── modules  # 子模块 , 可以依赖上层资源（user和project级别）
    │       │   └── profile
    │       │       └── views
    │       │           └── Profile.vue
    │       ├── service
    │       │   └── UserService.js
    │       ├── transformer
    │       │   └── UserTransformer.js
    │       └── views
    │           └── User.vue
    └── views
```

**Comment by fengmumu1** [comment]
对啊，我就是喜欢这种下放到页面级别的分层结构

**Comment by betgar** [comment]
文中的分层思想其实只是维度不同，和以前的image, pages, css, js这种资源型的分层一样，其实应该用模块化了，模块内外也要隔离，子模块之间也要隔离。这种分层优势就是迭代变动，影响范围可控。

**Comment by fenfenraorao** [comment]
你好，上面有关api部分，我理解是，比如:用户相关的api，展示用户信息的api放在src/api/modules/UserPublicApi.js里面，修改用户信息的api放在src/modules/user/api/ UserApi.js里面，不知道是不是这个意思？那src/modules/api.js里面放什么呢？

**Comment by xiaobutiaoer** [comment]
> 你的这个问题很好回答，其实只需要转变一下思路即可。按照模块化的思想，把这个分层移转换为如下结构，我自己分的。
> 
> ```
> fe-domain
> └── src
>     ├── api  # 全局api，可以隔离模块内部api和外部api
>     │   ├── api.js   
>     │   └── modules
>     │       └── UserPublicApi.js
>     ├── App.vue
>     ├── common   # 公共模块
>     │   └── http.js
>     ├── components  # 组件
>     │   ├── Nav.vue
>     │   └── Table.vue
>     ├── main.js
>     ├── modules  # 模块
>     │   └── user   
>     │       ├── api  # user 模块api层，public + private api都在这里集中
>     │       │   └── UserApi.js
>     │       ├── common
>     │       │   └── utils.js
>     │       ├── components
>     │       │   ├── Avatar.vue
>     │       │   └── List.vue
>     │       ├── modules  # 子模块 , 可以依赖上层资源（user和project级别）
>     │       │   └── profile
>     │       │       └── views
>     │       │           └── Profile.vue
>     │       ├── service
>     │       │   └── UserService.js
>     │       ├── transformer
>     │       │   └── UserTransformer.js
>     │       └── views
>     │           └── User.vue
>     └── views
> ```

这样抽离就没什么必要了，只是相当于增加了数据处理
让清洗过的数据增加适用性，尽可能的适合同一项目中多个地方的需求比较合适
